import "./globals.css";
import type { Metadata } from "next";

import { Gantari } from "next/font/google";

const gantari = Gantari({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bi' News",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={gantari.className}>{children}</body>
    </html>
  );
}
